-- ============================================================
-- portafolio — Schema Definitivo
-- ============================================================

BEGIN;

DROP TABLE IF EXISTS pf_pro_tech CASCADE;
DROP TABLE IF EXISTS pf_pro_lang CASCADE;
DROP TABLE IF EXISTS pf_projects CASCADE;
DROP TABLE IF EXISTS pf_technologies CASCADE;
DROP TABLE IF EXISTS pf_languages CASCADE;
DROP TABLE IF EXISTS pf_url CASCADE;
DROP TABLE IF EXISTS pf_urlgrp CASCADE;

CREATE TABLE IF NOT EXISTS pf_urlgrp (
    id_urlgrp INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL,
    is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pf_languages (
    id_language INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    img_url VARCHAR(256),
    is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pf_technologies (
    id_technology INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    img_url VARCHAR(256),
    is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pf_projects (
    id_project INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    img_url VARCHAR(256),
    repo_url VARCHAR(512),
    app_url VARCHAR(512),
    is_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pf_pro_lang (
    id_project INTEGER NOT NULL,
    id_language INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id_project, id_language),
    CONSTRAINT fk_pro_lang_project FOREIGN KEY (id_project)
        REFERENCES pf_projects(id_project) ON DELETE RESTRICT,
    CONSTRAINT fk_pro_lang_language FOREIGN KEY (id_language)
        REFERENCES pf_languages(id_language) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS pf_pro_tech (
    id_project INTEGER NOT NULL,
    id_technology INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id_project, id_technology),
    CONSTRAINT fk_pro_tech_project FOREIGN KEY (id_project)
        REFERENCES pf_projects(id_project) ON DELETE RESTRICT,
    CONSTRAINT fk_pro_tech_technology FOREIGN KEY (id_technology)
        REFERENCES pf_technologies(id_technology) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS pf_url (
    id_url INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    link VARCHAR(512) NOT NULL,
    is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    id_urlgrp INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_url_urlgrp FOREIGN KEY (id_urlgrp)
        REFERENCES pf_urlgrp(id_urlgrp) ON DELETE RESTRICT
);

CREATE INDEX ix_urlgrp_name ON pf_urlgrp(name);
CREATE INDEX ix_urlgrp_is_enabled ON pf_urlgrp(is_enabled);
CREATE INDEX ix_url_name ON pf_url(name);
CREATE INDEX ix_url_is_enabled ON pf_url(is_enabled);
CREATE INDEX ix_url_id_urlgrp ON pf_url(id_urlgrp);
CREATE INDEX ix_languages_name ON pf_languages(name);
CREATE INDEX ix_technologies_name ON pf_technologies(name);
CREATE INDEX ix_projects_name ON pf_projects(name);
CREATE INDEX ix_projects_is_enabled ON pf_projects(is_enabled);
CREATE INDEX ix_pro_lang_id_project ON pf_pro_lang(id_project);
CREATE INDEX ix_pro_lang_id_language ON pf_pro_lang(id_language);
CREATE INDEX ix_pro_tech_id_project ON pf_pro_tech(id_project);
CREATE INDEX ix_pro_tech_id_technology ON pf_pro_tech(id_technology);

COMMIT;
